In [1]:
# Importo las librerías Necesarias 
import numpy as np  # Importo algebra Lineal
import matplotlib.pyplot as plt # Importo librería de gráficos

In [2]:
A=np.array([[1, -3, -2],[2, -4, -3],[-3, 6, 8]])
b=np.array([[6], [8], [-5]])

In [3]:
print(A)
print(b)

[[ 1 -3 -2]
 [ 2 -4 -3]
 [-3  6  8]]
[[ 6]
 [ 8]
 [-5]]


In [4]:
x=np.linalg.solve(A,b)
print(x)

[[ 1.]
 [-3.]
 [ 2.]]


In [6]:
A.dot(x)

array([[ 6.],
       [ 8.],
       [-5.]])